import './globals.css'

import { type Metadata } from 'next'
import { Saira } from 'next/font/google'

import { Header } from '@/ui/components'

const font = Saira({ subsets: ['latin'], variable: '--font-primary' })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body
				className={`${font.className} flex w-full items-center justify-center px-5`}
			>
				<div className="w-full max-w-[1120px]">
					<Header />
					{children}
				</div>
			</body>
		</html>
	)
}
